### ISSUE TITLE
/b tree does not place trees in paper 1.14.2

### ISSUE THREAD

**Issue by WhyAreAllTheseTaken** [TVPT/VoxelSniper#354] opened 2020-03-19 18:23 UTC
Expected behaviour:
The /b tree tree command should place a tree when right clicking with the arrow.

Experienced behaviour:
No tree is placed and the following exception is generated:

```
[18:15:55] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to VoxelSniper v5.172.0-SNAPSHOT
java.lang.AbstractMethodError: com.thevoxelbox.voxelsniper.util.UndoDelegate.setBlockData(IIILorg/bukkit/block/data/BlockData;)Z
	at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.generateTree(CraftWorld.java:846) ~[patched_1.14.4.jar:git-Paper-243]
	at com.thevoxelbox.voxelsniper.brush.TreeSnipeBrush.single(TreeSnipeBrush.java:41) ~[?:?]
	at com.thevoxelbox.voxelsniper.brush.TreeSnipeBrush.arrow(TreeSnipeBrush.java:85) ~[?:?]
	at com.thevoxelbox.voxelsniper.brush.Brush.perform(Brush.java:76) ~[?:?]
	at com.thevoxelbox.voxelsniper.Sniper.snipe(Sniper.java:285) ~[?:?]
	at com.thevoxelbox.voxelsniper.VoxelSniperListener.onPlayerInteract(VoxelSniperListener.java:113) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor722.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-243]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-243]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-243]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-243]
	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:454) ~[patched_1.14.4.jar:git-Paper-243]
	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:421) ~[patched_1.14.4.jar:git-Paper-243]
	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:417) ~[patched_1.14.4.jar:git-Paper-243]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1400) ~[patched_1.14.4.jar:git-Paper-243]
	at net.minecraft.server.v1_14_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28) ~[patched_1.14.4.jar:git-Paper-243]
	at net.minecraft.server.v1_14_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5) ~[patched_1.14.4.jar:git-Paper-243]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-243]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-243]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-243]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-243]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-243]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-243]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-243]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-243]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1088) ~[patched_1.14.4.jar:git-Paper-243]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-243]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

Additional Information:
Paper: git-paper-243 (implementing 1.14.2-R0.1-SNAPSHOT)
VoxelSniper: 5.172.0-SNAPSHOT

**Comment by gabizou** [comment] 2020-05-02 21:43
Duplicate of #328 VoxelSniper hasn't been updated to support newer versions of Bukkit for MC 1.13+ yet.

**Closed as completed by gabizou** 2020-05-02 21:43 UTC
Labels: bukkit
